language: python
sudo: false
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - pip install -U pip codacy-coverage
  - pip install -U ".[test]"
script:
  - coverage run -m pytest --flake8
  - coverage report
after_script:
  - coverage xml
  - python-codacy-coverage -r coverage.xml
