language: python
sudo: false
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
install:
  - pip install -U pip
  - make install
  - pip install codacy-coverage
script: make fulltest
after_script: python-codacy-coverage -r coverage.xml
